### ISSUE TITLE
Generated docs sometimes have ansi escape control chars

### ISSUE THREAD

**Issue by ninmonkey** [StartAutomating/HelpOut#116]
Sometimes running HelpOut files include ansi escape sequences like the file `Get-GitLoggerSql.md` from https://github.com/StartAutomating/GitLogger/pull/13 

## Example Output

```md
## Syntax
```PowerShell
[32;1msyntaxItem[0m
[32;1m[0m```[0m
[32;1m[0m```PowerShell[0m
[32;1m[0m[32;1m----------[0m
[32;1m[0m[32;1m[0m```[0m
[32;1m[0m[32;1m[0m```PowerShell[0m
[32;1m[0m[32;1m[0m{@{name=Get-GitLoggerSql; CommonParameters=True; parameter=System.Object[]}}[0m
[32;1m[0m[32;1m[0m```[0m
```
That was fixed by toggling `PlainText` mode,

```ps1
$__originalOutputRendering = $PSStyle.OutputRendering
$PSStyle.OutputRendering = [System.Management.Automation.OutputRendering]::PlainText
Save-MarkdownHelp -Module $GitLoggerLoaded.Name -PassThru -SkipCommandType Alias
$PSStyle.OutputRendering = $__originalOutputRendering
```
- That is weird, because `HelpOut`'s git action appears to enable `Ansi` mode 
- Even after stripping ansi, I'm not sure if that's expected output

**Comment by StartAutomating** [comment]
@ninmonkey this appears to be the case when a topic does not actually have help.

I would rather users see a clear error somewhere for this circumstance (but do not want it to fail a build).

Therefore, I'm ok with this behavior as-is for now.  If you feel strongly, feel free to make a case.
