### ISSUE TITLE
Sudden confusion

### ISSUE THREAD

**Issue by potatoqualitee** [StartAutomating/HelpOut#154]
I could have sworn HelpOut used to strip out the help in allcommands.ps1?

I thought that my old dbatools outputs were like 1.4mb and now its 7. When i looekd inside, it both expoted the proper XML but it also has it in the ps1 file as well. Here's my command: 

```
 Install-Maml -FunctionRoot public, private\functions -Module dbatools -Compact -NoVersion -ScriptName dbatools.ps1
```

**Comment by StartAutomating** [comment]
@potatoqualitee 

It looks like a change last year [took out this functionality while doing some refactoring](https://github.com/StartAutomating/HelpOut/commit/39d217e292f358322fbe012335c905f450de1e7d)

Sorry about that.

I'll be re-adding this functionality shortly, and will put it behind an optional switch.
