### ISSUE TITLE
Docs generate same docs for function names and aliases

### ISSUE THREAD

**Issue by PrzemyslawKlys** [StartAutomating/HelpOut#160]
This relatees to:
- #159 

Docs shouldn't contain aliases, but more be referenced in the main function somehow

![image](https://github.com/StartAutomating/HelpOut/assets/15063294/b39c6ebb-6c2c-4f05-aa55-7b37fc7b04a2)

![image](https://github.com/StartAutomating/HelpOut/assets/15063294/c3eda9f9-dab1-412a-88e6-06e5f0e1db75)

**Comment by StartAutomating** [comment]
@PrzemyslawKlys  this one's easy.  You can use -SkipCommandType/-ExcludeCommandType to skip commands of a particular type (like aliases)

I think that we can agree to disagree on aliases being documented by default (I use them fairly extensively, and want the docs to work either way).

Let me know if you're ok closing this, now that you know about the option on Save-MarkdownHelp

**Comment by PrzemyslawKlys** [comment]
It's fine :)
