### ISSUE TITLE
Trim More than 3 Newlines into 2 Newlines

### ISSUE THREAD

**Issue by PrzemyslawKlys** [StartAutomating/HelpOut#161]
Is it possible to remove all the whitespace that is there? 

![image](https://github.com/StartAutomating/HelpOut/assets/15063294/c57bcc9b-2de4-4abf-9d55-2a3510d9dc8d)

Seems to be unnecessary and it looks weird in RAW. While preview doesn't care, it would be nicer without it.

**Comment by StartAutomating** [comment]
@PrzemyslawKlys  I can try to slim it down a bit.... I'm somewhat wary of doing so, as I've had a couple of earlier builds where I've trimmed too much and preview looks quite bad.  Will see what I can do.
