### ISSUE TITLE
`Get/Save-Maml -IncludeAlias(es)`

### ISSUE THREAD

**Issue by potatoqualitee** [StartAutomating/HelpOut#178]
Any chance some sort of support can be added for aliases? maybe duplicate info if I say -IncludeAliases? 

I'm using HelpOut in my GPTs and I upload the XML files but now that New-UDDashboard is New-UDApp, it's losing its mind.

But then `get-help -examples new-uddashboard` returns some results for New-UDApp

**Comment by StartAutomating** [comment]
@potatoqualitee are you talking about `Save-Maml`?  `Save-MarkdownHelp` has a few aliasing options.
